name: Top20 Automation

on: [push]

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Node Modules
        run: |
          npm install
      - name: Run Linter
        run: |
          npm run lint
      - name: Sec Test
        run: |
          npm audit --audit-level=moderate
      - name: Unit Tests
        run: |
          npm test
